# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1534392703);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1534392823);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1534400604);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1534392583);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1534393063);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1534392463);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1534305350);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1534392943);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1533918140);
user_pref("browser.laterrun.bookkeeping.sessionCount", 11);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 62);
user_pref("browser.newtabpage.activity-stream.impressionId", "{a697b1d5-a459-4c1d-8454-804847368288}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1533873600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1534393616);
user_pref("browser.onboarding.notification.prompt-count", 4);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1534402358748");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1534404179748");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1534400586116");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1534404186116");
user_pref("browser.search.countryCode", "MN");
user_pref("browser.search.region", "MN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180406121424");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1534393557");
user_pref("browser.slowStartup.averageTime", 13399);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20180406121424");
user_pref("browser.startup.homepage_override.mstone", "59.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1533918172298");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "59.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 4);
user_pref("extensions.blocklist.pingCountVersion", 4);
user_pref("extensions.databaseSchema", 24);
user_pref("extensions.getAddons.cache.lastUpdate", 1534392704);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180406121424");
user_pref("extensions.lastAppVersion", "59.0.2");
user_pref("extensions.lastPlatformVersion", "59.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pocket.settings.test.panelSignUp", "v1");
user_pref("extensions.shield-recipe-client.first_run", false);
user_pref("extensions.shield-recipe-client.user_id", "836e1c4c-969e-4941-a66b-e4374305438f");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"3845d80d-b235-4ef9-a9c6-a3031a1bd66b\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1534394196);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1533918187);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180406121424");
user_pref("media.gmp-manager.lastCheck", 1534392679);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1534306560);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.blocklist.addons.checked", 1534392768);
user_pref("services.blocklist.clock_skew_seconds", 55);
user_pref("services.blocklist.gfx.checked", 1534392768);
user_pref("services.blocklist.last_etag", "\"1534382538298\"");
user_pref("services.blocklist.last_update_seconds", 1534392768);
user_pref("services.blocklist.onecrl.checked", 1534392768);
user_pref("services.blocklist.pinning.checked", 1534392768);
user_pref("services.blocklist.plugins.checked", 1534392768);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1534306560);
user_pref("toolkit.startup.last_success", 1534393543);
user_pref("toolkit.telemetry.cachedClientID", "c8bf3478-809f-4b45-afca-96cbb1e8a6e9");
user_pref("toolkit.telemetry.previousBuildID", "20180406121424");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
